Vivo.web/Areas/Wechat/Controllers/PlanCategoryController.cs
using Vivo.BLLFactory;
using Vivo.IBLL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using Vivo.Model;
using Tool;
using System.Dynamic;

namespace Vivo.web.Areas.Wechat.Controllers
{
    public class PlanCategoryController : BaseMPController
    {

        public ActionResult Index(int page = 1)
        {
            var list = PlanCategoryBLL.GetList(p =>  p.ID != Wechat.Controllers.ResearchPersonController.PlanCategoryPersonalID);
            list = list.OrderByDescending(p => p.Enable ).ThenByDescending(p=>p.ID);
            IPagedList<PlanCategoryInfo> result = list.ToPagedList(page, PageSize);
            return View(result);
        }

        public ActionResult Create()
        {
            return View();
        }


        public ActionResult Edit(int id)
        {
            PlanCategoryInfo info = PlanCategoryBLL.GetList(p => p.ID == id).FirstOrDefault();


            return View(info);
        }

        [AllowAnonymous]
        public ActionResult Detail(int id)
        {
            PlanCategoryInfo info = PlanCategoryBLL.GetList(p => p.ID == id).FirstOrDefault();


            return View(info);
        }


    }
}

Vivo.web/Areas/Wechat/Views/PlanCategory/Create.cshtml
@using Vivo.Model;
@using Vivo.IBLL;
@using Vivo.BLLFactory;
@model PlanCategoryInfo

@{
    ViewBag.Title = "新建";
    Layout = "~/Areas/Wechat/Views/Shared/_Layout.cshtml";
}

@section head{
    <script type="text/javascript">
        function OnSuccess(data) {
            alert(data.ErrorMsg);
            if (data.ErrorCode != 0) {
                return;
            }
            location.href = "@Url.Action("Detail")/"+data.Data.ID;

        }
        function OnBegin() {

        }
    </script>
}

@using (Ajax.BeginForm("Create", "PlanCategory", new { area = "MP" }, new AjaxOptions { HttpMethod = "Post", OnSuccess = "OnSuccess", OnBegin = "OnBegin", LoadingElementId = "loadingToast" }))
{
    @Html.AntiForgeryToken()
    <div class="weui_cells">

        <div class="weui_cell">
            <div class="weui_cell_hd"><label class="weui_label">名称</label></div>
            <div class="weui_cell_bd weui_cell_primary">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "weui_input" } })
           </div>
        </div>

        <div class="weui_cell weui_cell_switch">
            <div class="weui_cell_hd weui_cell_primary">是否可用</div>
            <div class="weui_cell_ft">
                @Html.CheckBoxFor(model => model.Enable, new { @class = "weui_switch", @checked = "checked" })
            </div>
        </div>
        <div class="weui_btn_area">
            <input type="submit" value="提交" class="weui_btn weui_btn_primary" />
        </div>
    </div>
}

Vivo.web/Areas/Wechat/Views/PlanCategory/Detail.cshtml
@using Vivo.Model;
@using Vivo.IBLL;
@using Vivo.BLLFactory;
@model PlanCategoryInfo

@{
    ViewBag.Title = "详细信息";
    Layout = "~/Areas/Wechat/Views/Shared/_Layout.cshtml";
    IPowerActionInfoService PowerActionBLL = AbstractFactory.CreatePowerActionInfoService();
}
@section head{

    <script type="text/javascript">
        function BtnDelete_Click() {
            if (!confirm("确定要删除吗？")) {
                return;
            }
            $.post("@Url.Action("Delete",new { area="MP",ID=Model.ID})", function (data) {
                alert(data.ErrorMsg);
                if (data.ErrorCode == 0) {
                    location.href = "@Url.Action("Index")";
                }
            });
        }

    </script>

}




<div class="weui_cells">
    <div class="weui_cell">
        <div class="weui_cell_hd weui_cell_primary"><label class="weui_label">名称</label></div>
        <div class="weui_cell_ft">
            @Model.Name
        </div>
    </div>
    <div class="weui_cell">
        <div class="weui_cell_hd weui_cell_primary">是否可用</div>
        <div class="weui_cell_ft">
            @(Model.Enable ? "正常" : "禁用")
        </div>
    </div>
</div>
<div style="height:40vh;"></div>
@if (PowerActionBLL.PowerCheck(PowerInfo.P_评课管理.PP组织调研.PPP分组管理.编辑))
{
    <a href="@Url.Action("Edit",new { ID=Model.ID})" class="weui_btn weui_btn_primary" style="margin:15px;">
        前住修改
    </a>
}
@if (PowerActionBLL.PowerCheck(PowerInfo.P_评课管理.PP组织调研.PPP分组管理.删除))
{
    <a href="javascript:BtnDelete_Click();" class="weui_btn weui_btn_warn" style="margin:15px;">
        删除
    </a>
}

Vivo.web/Areas/Wechat/Views/PlanCategory/Edit.cshtml
@using Vivo.Model;
@using Vivo.IBLL;
@using Vivo.BLLFactory;
@model PlanCategoryInfo

@{
    ViewBag.Title = "编辑";
    Layout = "~/Areas/Wechat/Views/Shared/_Layout.cshtml";
    IPowerActionInfoService PowerActionBLL = AbstractFactory.CreatePowerActionInfoService();

}
@section head{
    <script type="text/javascript">
        function OnSuccess(data) {
            alert(data.ErrorMsg);
            if (data.ErrorCode != 0) {
                return;
            }
            location.href = "@Url.Action("Detail", new { ID = Model.ID })";

        }
        function OnBegin() {
            //do something before post data

        }

    </script>



}


@using (Ajax.BeginForm("Edit", "PlanCategory", new { area = "MP" }, new AjaxOptions { HttpMethod = "post", OnSuccess = "OnSuccess", OnBegin = "OnBegin", LoadingElementId = "loadingToast" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID)

    <div class="weui_cells">

        <div class="weui_cell">
            <div class="weui_cell_hd"><label class="weui_label">名称</label></div>
            <div class="weui_cell_bd weui_cell_primary">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "weui_input" } })
            </div>
        </div>

        <div class="weui_cell weui_cell_switch">
            <div class="weui_cell_hd weui_cell_primary">是否可用</div>
            <div class="weui_cell_ft">
                @Html.CheckBoxFor(model => model.Enable, new { @class = "weui_switch", @checked = "checked" })
            </div>
        </div>
        <div class="weui_btn_area">
            <input type="submit" value="提交" class="weui_btn weui_btn_primary" />
        </div>
    </div>



}

Vivo.web/Areas/Wechat/Views/PlanCategory/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@using Vivo.Model;
@using Vivo.IBLL;
@using Vivo.BLLFactory;

@model IPagedList<PlanCategoryInfo>

@{
    ViewBag.Title = "组织调研分组管理";
    Layout = "~/Areas/Wechat/Views/Shared/_Layout.cshtml";
    IPowerActionInfoService PowerActionBLL = (IPowerActionInfoService)ViewBag.PowerActionBLL;
    IUserInfoService UserBLL = AbstractFactory.CreateUserInfoService();
}
@section head{
    <style type="text/css">
        .SpanMajorUser {
            color:#F60;
            font-weight:bold;
        }
    </style>
}

<div class="bd">
    @if (PowerActionBLL.PowerCheck(PowerInfo.P_评课管理.PP组织调研.PPP分组管理.增加))
    {
        <a href="@Url.Action("Create")" class="weui_btn weui_btn_primary" title="添加" style="margin:15px;">
            添加
        </a>
    }
</div>


<div class="bd">

    <div class="weui_panel">
        <div class="weui_panel_bd">
            @foreach (var item in Model)
            {
                <div class="weui_cells weui_cells_access">
                    <a class="weui_cell" href="@Url.Action("Detail",new { ID=item.ID})">
                        <div class="weui_cell_bd weui_cell_primary">
                            <p>@item.Name</p>
                        </div>
                    </a>

                </div>
            }
        </div>
    </div>

</div>



<div style="text-align:center">
    @Html.PagedListPager((IPagedList)Model,
    page => Url.Action("Index", new { page = page }),
    new PagedListRenderOptions
    {
        LinkToPreviousPageFormat = "上一页",
        LinkToNextPageFormat = "下一页",
        MaximumPageNumbersToDisplay = 0,
        Display = PagedListDisplayMode.IfNeeded,
        DisplayEllipsesWhenNotShowingAllPageNumbers = true
    }
    )
</div>