Vivo.web/Areas/MP/Controllers/HomeController.cs
using Vivo.BLLFactory;
using Vivo.IBLL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vivo.Model;
using System.Data.Entity;

namespace Vivo.web.Areas.MP.Controllers
{

    [AllowAnonymous]
    public class HomeController : BaseMPUnFilterController
    {
        // GET: MP/Home
        public ActionResult Index()
        {
            return View();
        }
        //public ActionResult menu()
        //{
        //    var menus = PowerActionBLL.GetByUserID(CurrentUser.ID).Where(p => p.Enable && p.TypeEnum == (int)SysEnum.PowerActionType.菜单权限).ToList();


        //    return View(menus);
        //}
        [AllowAnonymous]
        public ActionResult menuTemp()
        {

            return View();
        }
        [AllowAnonymous]
        public ActionResult Note()
        {
           
            return View();
        }
        public ActionResult Top()
        {
            IUserInfoService UserBLL = AbstractFactory.CreateUserInfoService();
            return View(UserBLL.GetCurrent());
        }

    }
}

Vivo.web/Areas/MP/Controllers/PlanController.cs
using Vivo.BLLFactory;
using Vivo.IBLL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using Vivo.Model;
using Tool;
using System.Dynamic;

namespace Vivo.web.Areas.MP.Controllers
{
    public class PlanController : BaseController
    {

        public ActionResult Index(int page = 1)
        {


            var list = PlanBLL.GetList(p => true);
            list = list.OrderBy(a=>a.AgenterName).ThenBy(a=>a.DateBegin).ThenBy(a=>a.SortID);
            IPagedList<PlanInfo> result = list.ToPagedList(page, 50);
            return View(result);
        }

        public ActionResult Create()
        {
            ViewBag.listPrizeType = Common.EnumToSelectListItem(typeof(SysEnum.PrizeType));
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(PlanInfo info)
        {
            info.Enable = true;
            PlanBLL.Create(info);
            if (info.ID > 0)
            {
                return Json(new APIJson(0, "添加成功"));
            }
            return Json(new APIJson(-1, "添加失败"));
        }

        public ActionResult Edit(int id)
        {
            ViewBag.listPrizeType = Common.EnumToSelectListItem(typeof(SysEnum.PrizeType));
            PlanInfo info = PlanBLL.GetList(p => p.ID == id).FirstOrDefault();


            return View(info);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(PlanInfo info)
        {
            PlanInfo infoExist = PlanBLL.GetList(p => p.ID == info.ID).FirstOrDefault();
            if (null == infoExist)
            {
                return Json(new APIJson(-1, "parms error"));
            }
            info.Enable = true;
            infoExist.DateBegin = info.DateBegin;
            infoExist.DateEnd = info.DateEnd;
            infoExist.AgenterName = info.AgenterName;
            infoExist.Mount = info.Mount;
            infoExist.Enable = info.Enable;
            infoExist.MarketLevel = info.MarketLevel;
            infoExist.TypeFlag = info.TypeFlag;
            infoExist.SortID = info.SortID;
            if (PlanBLL.Edit(infoExist))
            {
                return Json(new APIJson(0, "提交成功", info));
            }
            return Json(new APIJson(-1, "提交失败", info));
        }


        [HttpPost]
        public ActionResult Delete(int id)
        {
            PlanInfo info = PlanBLL.GetList(p => p.ID == id).FirstOrDefault();
            if (null == info)
            {
                return Json(new APIJson(-1, "删除失败，参数有误", info));
            }
            if (PlanBLL.Delete(info))
            {
                return Json(new APIJson(0, "删除成功", info));
            }
            return Json(new APIJson(-1, "删除失败，请重试", info));
        }

    }
}

Vivo.web/Areas/MP/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using Vivo.Model;
using Vivo.IBLL;
using Vivo.BLLFactory;
using Tool;
using System.Threading;
using System.Text.RegularExpressions;
using System.Data;
using System.IO;

namespace Vivo.web.Areas.MP.Controllers
{
    public class UserController : BaseMPController
    {

        public ActionResult Index(int page = 1)
        {
            GetSelectList();
            IQueryable<UserInfo> list = GetDataList();
            var result = list.ToPagedList(page, PageSize);
            return View(result);
        }
        private void GetSelectList()
        {
            ViewBag.listRule = RuleBLL.GetList(a => a.Enable).Select(p => new SelectListItem() { Text = p.Name, Value = p.ID.ToString() }).ToList();
            ViewBag.listMemberGroup = MemberGroupBLL.GetList(a => a.Enable).Select(p => new SelectListItem() { Text = p.Name, Value = p.ID.ToString() }).ToList();
            IEnumerable<SelectListItem> listDepartmentID = DepartmentBLL.GetList(p => p.Enable == true).OrderBy(a=>a.Name).Select(p => new SelectListItem { Text = p.Name, Value = p.ID.ToString() }).ToList();
            if (!PowerActionBLL.PowerCheck(PowerInfo.P_系统管理.PP系统帐户管理.PPP用户管理.查看所有帐户))
            {
                listDepartmentID = listDepartmentID.Where(a => a.Value == CurrentUser.DepartmentID.ToString());
            }
            ViewBag.listDepartment = listDepartmentID;
            IEnumerable<SelectListItem> listEnableStatus = Common.EnumToSelectListItem(typeof(SysEnum.EnableStatus.EnumEnableStatus));
            ViewBag.EnableStatus = listEnableStatus;

        }


        private IQueryable<UserInfo> GetDataList()
        {
            IQueryable<UserInfo> list = UserBLL.GetList(p => true);

            int PowerGroupID = Function.GetRequestInt("PowerGroupID");
            int DepartmentID = Function.GetRequestInt("DepartmentID");
            int EnableStatus = Function.GetRequestInt("EnableStatus");
            int SubjectID = Function.GetRequestInt("SubjectID");
            string Name = Function.GetRequestString("Name");

            if (!PowerActionBLL.PowerCheck(PowerInfo.P_系统管理.PP系统帐户管理.PPP用户管理.查看所有帐户))
            {
                DepartmentID = CurrentUser.DepartmentID;
                if (!PowerActionBLL.PowerCheck(PowerInfo.P_系统管理.PP系统帐户管理.PPP用户管理.查看当前单位帐户))
                {
                    list = list.Where(a => a.ID == CurrentUser.ID);
                }
            }


            if (PowerGroupID > 0)
            {
                list = list.Where(p => p.RuleInfo.Any(r => r.ID == PowerGroupID));
                ViewBag.DdlPowerGroupID = PowerGroupID;
            }
            if (DepartmentID > 0)
            {
                list = list.Where(p => p.DepartmentID == DepartmentID);
                ViewBag.DdlDepartmentID = DepartmentID;
            }

            if (EnableStatus > 0)
            {
                list = list.Where(p => p.Enable == (EnableStatus == (int)SysEnum.EnableStatus.EnumEnableStatus.启用));
                ViewBag.DdlEnableStatus = EnableStatus;
            }
            if (!string.IsNullOrEmpty(Name))
            {
                list = list.Where(p => p.Name.Contains(Name)
                 || p.WechatNameNick.Contains(Name)
                 || p.IDCard.Contains(Name)
                 || p.Code.Contains(Name));
                ViewBag.TxtName = Name;
            }
            if (SubjectID > 0)
            {
                list = list.Where(p => p.TypeID == SubjectID);
                ViewBag.DdlSubjectID = SubjectID;
            }
            

            list = list.OrderByDescending(p => p.Enable)
                .ThenByDescending(p=>p.DepartmentID)
                .ThenByDescending(p => p.ID);


            return list;
        }

        public ActionResult Export()
        {
            IQueryable<UserInfo> list = GetDataList();
            DataTable dt = new DataTable();
            dt.Columns.Add("ID");
            dt.Columns.Add("登录名");
            dt.Columns.Add("真实姓名");
            dt.Columns.Add("单位名称");
            dt.Columns.Add("是否启用");
            dt.Columns.Add("微信OpenID");
            dt.Columns.Add("微信昵称");
            dt.Columns.Add("创建时间");
            dt.Columns.Add("角色");
            dt.Columns.Add("学科");

            foreach (var item in list)
            {
                DataRow dr = dt.NewRow();
                dr["ID"] = item.ID;
                dr["登录名"] = item.Code;
                dr["真实姓名"] = item.Name;
                dr["单位名称"] = item.DepartmentInfo.Name;
                dr["是否启用"] = item.Enable ? "可用" : "x";
                dr["微信OpenID"] = item.WechatOpenID;
                dr["微信昵称"] = item.WechatNameNick;
                dr["创建时间"] = item.CreateDate;
                dr["角色"] = string.Join("/", item.RuleInfo.Select(r => r.Name));
                dr["学科"] = string.Join("/", item.SubjectInfo.Select(r => r.Name));
                dt.Rows.Add(dr);
            }
            string FilePath = "/Content/Export/User/";
            string FileFullPath = Server.MapPath(FilePath);
            if (!Directory.Exists(FileFullPath))
            {
                Directory.CreateDirectory(FileFullPath);

            }
            string FileName = DateTime.Now.ToFileTime().ToString() + ".xlsx";
            NPOIHelper.Export(dt, FileFullPath + FileName);
            return Redirect(FilePath + FileName);
        }

        public ActionResult Create()
        {
            GetSelectList();
            return View();
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(UserInfo info)
        {

            UserInfo infoExist = UserBLL.GetList(p => p.Name == info.Name || p.Code == info.Code).FirstOrDefault();

            if (info.DepartmentID <= 0)
            {
                return Json(new APIJson("请选择所在部门"));
            }
            if (null != infoExist)
            {
                return Json(new APIJson("登录名和姓名重复，请起用其它名字"));
            }
            if (string.IsNullOrEmpty(info.Name))
            {
                return Json(new APIJson("姓名不能为空"));
            }
            if (string.IsNullOrEmpty(info.Code))
            {
                info.Code = info.Name;
            }
            if (!string.IsNullOrEmpty(info.PassWord))
            {
                bool IsPassWordValidate = ValidatePassWord(info);
                if (!IsPassWordValidate)
                {
                    return Json(new APIJson("密码必需包含数字、字母，并且长度在8到16位"));
                }
            }
            else
            {
                info.PassWord = "lw123456";
            }

            if (string.IsNullOrEmpty(info.Email))
            {
                info.Email = string.Empty;
            }
            if (string.IsNullOrEmpty(info.Tel))
            {
                info.Tel = string.Empty;
            }
            if (string.IsNullOrEmpty(info.IDCard))
            {
                info.IDCard = string.Empty;
            }


            info.PassWord = Tool.Md5Helper.Md5(info.PassWord);
            info.CreateDate = DateTime.Now;
            info.LastDate = DicInfo.DateZone;
            info.LocationX = info.LocationY = 0;
            info.WechatOpenID = string.Empty;
            info.WechatNameNick = string.Empty;
            info.WechatHeadImg = string.Empty;
            info.Sex = string.Empty;
            if (info.DefaultSubjectID>0)
            {
                SubjectInfo infoSubject = SubjectBLL.GetList(a => a.ID == info.DefaultSubjectID).FirstOrDefault();
                if (null!=infoSubject)
                {
                    info.SubjectInfo.Add(infoSubject);
                }
            }
            info = UserBLL.Create(info);
            if (info.ID > 0)
            {
                return Json(new APIJson(0, "添加成功", new { ID = info.ID,Name=info.Name }));
            }
            return Json(new APIJson(-1, "添加失败"));
        }

        public static bool ValidatePassWord(UserInfo info)
        {
            //var regex = new Regex(@"
            //                    (?=.*[0-9])                     #必须包含数字
            //                    (?=.*[a-zA-Z])                  #必须包含小写或大写字母
            //                    (?=([\x21-\x7e]+)[^a-zA-Z0-9])  #必须包含特殊符号
            //                    .{6,16}                         #至少8个字符，最多30个字符
            //                    ", RegexOptions.Multiline | RegexOptions.IgnorePatternWhitespace);
            var regex = new Regex(@"
                                (?=.*[0-9])                     #必须包含数字
                                (?=.*[a-zA-Z])                  #必须包含小写或大写字母
                                ", RegexOptions.Multiline | RegexOptions.IgnorePatternWhitespace);
            if (string.IsNullOrEmpty(info.PassWord))
            {
                return false;
            }
            bool IsPassWordValidate = regex.IsMatch(info.PassWord);
            return IsPassWordValidate;
        }

        //public static bool ValidateEmail(UserInfo info)
        //{
        //    var regex = new Regex(@"^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,5})+$", RegexOptions.Multiline | RegexOptions.IgnorePatternWhitespace);
        //    bool IsEmailValidate = regex.IsMatch(info.Email);
        //    return IsEmailValidate;
        //}

        public ActionResult Edit(int id)
        {
            UserInfo info = UserBLL.GetList(p => p.ID == id).FirstOrDefault();
            if (null == info)
            {
                return Json(new APIJson("参数有误"));
            }

            GetSelectList();

            return View(info);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(UserInfo info)
        {
            UserInfo infoExist = UserBLL.GetList(p => p.ID != info.ID && (p.Name == info.Name || p.Code == info.Code)).FirstOrDefault();
            if (info.DepartmentID <= 0)
            {

Vivo.web/Areas/Wechat/Controllers/HomeController.cs
using Vivo.BLLFactory;
using Vivo.IBLL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vivo.Model;
using Vivo.web.Areas.Wechat.Models;

namespace Vivo.web.Areas.Wechat.Controllers
{
    [AllowAnonymous]
    public class HomeController : BaseMPUnFilterController
    {
        // GET: MP/Home
        public ActionResult Index()
        {

            ViewBag.WechatHeaderInfo = new WechatHeaderInfo() { HeadText = "首页" };
            return View();
        }
        public ActionResult API()
        {
            return View();
        }
    }
}

Vivo.web/Controllers/PrizeResultController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using Vivo.Model;
using Tool;


namespace Vivo.web.Controllers
{
    public class PrizeResultController : BaseController
    {
        public ActionResult C(PrizeResultInfo info)
        {

            
            if (string.IsNullOrEmpty(info.Name))
            {
                return Json(new APIJson(1, ""));
            }
            if (string.IsNullOrEmpty(info.Name) || info.Name.Length > 50)
            {
                return Json(new APIJson(2, ""));
            }
            if (string.IsNullOrEmpty(info.StoreAdd))
            {
                return Json(new APIJson(3, ""));
            }
            if (info.StoreAdd.Length>500)
            {
                return Json(new APIJson(4, ""));
            }
            if (!IsMobilePhone(info.Tel))
            {
                return Json(new APIJson(5, "手机号输入不正确，请重新输入!"));
            }
            if (info.SnNumber.Length!=15)
            {
                return Json(new APIJson(6, "SN!"));
            }
            if (string.IsNullOrEmpty(info.AreaName))
            {
                return Json(new APIJson(7, "Area!"));
            }

           var infoExist= PrizeResultBLL.GetList(a => a.SnNumber == info.SnNumber).FirstOrDefault();
            if (null==infoExist)
            {
                return Json(new APIJson(8, "SN not exist!"));
            }
            if (!string.IsNullOrEmpty(infoExist.Name))
            {
                var ExistOBJ = new {infoExist.ID,infoExist.Name,infoExist.IP,infoExist.StoreAdd,infoExist.Tel,infoExist.SnNumber,infoExist.CreateDate,infoExist.Result };
                return Json(new APIJson(-1, "Has Taken!",ExistOBJ));
            }
           // infoExist.IP = info.IP;
            infoExist.Name = info.Name;
            infoExist.StoreAdd = info.StoreAdd;
            infoExist.Tel = info.Tel;
            //infoExist.SnNumber=info
            infoExist.AreaName = info.AreaName;
            infoExist.CreateDate = DateTime.Now;
            //infoExist.Result
            if (PrizeResultBLL.Edit(infoExist))
            {
                var ExistOBJ = new { infoExist.ID, infoExist.Name, infoExist.IP, infoExist.StoreAdd, infoExist.Tel, infoExist.SnNumber, infoExist.CreateDate, infoExist.Result };
                return Json(new APIJson(0, "OK!", ExistOBJ));
            }
            else
            {
                return Json(new APIJson(9, "NotSavedYet!"));
            }
        }


        public static bool IsMobilePhone(string input)
        {
            if (input.Length!=10)
            {
                return false;
            }
            try
            {
                Convert.ToInt64(input);
                return true;
            }
            catch (Exception)
            {
                return false;
            }
        }

    }
}

Vivo.web/Areas/MP/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Vivo.web/Areas/MP/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <title></title>
    <script type="text/javascript">
        function ReloadLeft() {
            // window.open("/menu.aspx", "left");
            left.UpdateCount();
        }

        function changeFrameHeight() {
            var ifm = document.getElementsByName("left");
            ifm.height = document.documentElement.clientHeight;
            ifm = document.getElementsByName("main");
            ifm.height = document.documentElement.clientHeight;
        }
        window.onresize = function () {
            changeFrameHeight();
        } 
    </script>
</head>
<body style="background-color:#F1F2F6">
    <div class="container-fluid" style="padding:0;">
        <div class="row">
            <div class="col-md-2">
                <iframe src="/MP/Home/menuTemp"  style="width:200px;height:100%;min-height:100vh;"  onload="changeFrameHeight()"
                        name="left"  frameBorder="0" noresize="noresize" scrolling="No"></iframe>

            </div>
            <div class="col-md-10" style="padding-left:0px;">
                <iframe src="@Url.Action("index","PrizeResult")" style="width:100%;height:100%;min-height:100vh;" onload="changeFrameHeight()"
                        name="main" frameBorder="0" noresize="noresize" scrolling="yes" ></iframe>
            </div>
        </div>
    </div>
</body>
</html>

Vivo.web/Areas/MP/Views/Home/Note.cshtml
@using Vivo.Model;
@using Vivo.IBLL;
@using Vivo.BLLFactory;

@model Vivo.Model.UserInfo
@{
    ViewBag.Title = "Note";
    Layout = "~/Areas/MP/Views/Shared/_Layout.cshtml";

}

<div style="margin:20px">


    <div class="bs-example" data-example-id="contextual-panels">

        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title">当前系统版本V17.07.27</h3>
            </div>
            <div class="panel-body">

                <br />
                <br />
                <br />
                copy rights @@    all rights reserved

            </div>
        </div>
        @*<div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title">Panel title</h3>
                </div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>
            <div class="panel panel-warning">
                <div class="panel-heading">
                    <h3 class="panel-title">Panel title</h3>
                </div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>
            <div class="panel panel-danger">
                <div class="panel-heading">
                    <h3 class="panel-title">Panel title</h3>
                </div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>*@
    </div>

</div>

Vivo.web/Areas/MP/Views/Home/Top.cshtml
@using Vivo.Model;

@model Vivo.Model.UserInfo
@{
    ViewBag.Title = "Top";
    Layout = "~/Areas/MP/Views/Shared/_Layout.cshtml";
}
@section head{
<script type="text/javascript">
        function BtnLogin_Click() {
             $.get("@Url.Action("Logout", "Login", new { area = "MP" })", function () {
                location.href = "@Url.Action("index","Login")";
            });
        }
</script>

}

<nav class="navbar navbar-default" style="background-color:#F1F2F6;">
    <div class="navbar-inner">
        <div class="container-fluid">

            <a class="navbar-brand" href="javascript:top.location.reload()">
                <img src="~/images/logo.png" alt="Brand" style="width:20px;" />
            </a>
            <div class="collapse navbar-collapse" style="background:url(/images/Consolebanner.png) no-repeat 100% 0;background-repeat:no-repeat;">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="#">
                            <img src="@Model.WechatHeadImg" class="img-circle" style="width:20px;float:left;" />
                            @Model.Name

                        </a>
                    </li>
                    <li class="divider-vertical"></li>
                    <li>
                        <a href="javascript:BtnLogin_Click();">注销</a>
                    </li>
                    <li class="divider-vertical"></li>
                    <li>
                        <a href="@Url.Action("Pwd", "User")" tabindex="-1" target="main">修改密码</a>
                    </li>
                    <li class="divider-vertical"></li>
                    <li>
                        <a href="@Url.Action("ReLogin", "Login")" tabindex="-1" target="_parent">重新登录</a>
                    </li>
                    <li class="divider-vertical"></li>
                    <li>
                        <a href="javascript:parent.FullScreen();" tabindex="-1">全屏</a>
                    </li>
                    <li class="divider-vertical"></li>
                    <li>
                        <a href="javascript:parent.FullScreenCancel();" tabindex="-1">退出全屏</a>
                    </li>
                </ul>


                <ul class="nav navbar-nav">
                    <li >
                        <a href="javascript:top.location.reload()" style="color:#ff6a00;">荔湾区教育发展研究中心</a>
                    </li>
                </ul>
            </div>
            <!--/.nav-collapse -->
        </div>
    </div>
</nav>

Vivo.web/Areas/MP/Views/Home/menuTemp.cshtml
@using Vivo.Model;
@using Vivo.IBLL;
@using Vivo.BLLFactory;


@{
    Layout = "~/Areas/MP/Views/Shared/_Layout.cshtml";

}
@section head{
    <style type="text/css">
    </style>

}

<div class="list-group">
    <a href="#" class="list-group-item disabled">
        系统菜单
    </a>
    <a href="@Url.Action("index","PrizeResult")" target="main" class="list-group-item">抽奖记录</a>
    <a href="@Url.Action("index","Plan")" target="main" class="list-group-item">投放规则</a>
    <a href="@Url.Action("Edit","Profiles")" target="main" class="list-group-item">其它项设置</a>
</div>